### ISSUE TITLE
Any plans to share code for training?

### ISSUE THREAD

**Issue by JY-CCK** [EricLBuehler/xlora#18]
Hello, Authors.
Thank you for your excellent work.

Do you have any plans to share the training code?
After constructing my model following your instructions, it encountered an error.

This is my code for model.
```
model = AutoModelForCausalLM.from_pretrained(
        "mistralai/Mistral-7B-Instruct-v0.1",
        attn_implementation="flash_attention_2",
        torch_dtype=torch.bfloat16,
        device_map='auto',
        cache_dir=cache_dir,
    )
  model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
  model = xlora.add_xlora_to_model(
      model=model,
      xlora_config=xlora.xLoRAConfig(
          model.config.hidden_size,
          xlora_depth=4,
          device=torch.device("cuda"),
          adapters={
              "adapter_1": "upaya07/Arithmo2-Mistral-7B-adapter",
              "adapter_2": "Amar5000/mistral-7b-code-adapter-v2",
              "adapter_3": "vineetsharma/qlora-adapter-Mistral-7B-Instruct-v0.1-gsm8k",
              "adapter_4": "sandst1/mistral-sql-adapter-7b",
          },
      ),
      verbose=True,
  )
```

And error is,
 ```
 File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2744, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1958, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1964, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2040, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 503, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 254, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 289, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 318, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 254, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

I used huggingface library for SFT and tried with deepspeed zero2 and zero3 (both occured errors)

Thanks.

**Comment by EricLBuehler** [comment]
Hi @JY-CCK,

Could you please try to enable layerwise scalings? Additionally, if you could share a minimum reproducible example, that would be great! We did not encounter this error in our training and do not plan on releasing our training code.

> `model.config.use_cache = False  # silence the warnings. Please re-enable for inference!`

`use_cache` must be False due to our dual-forward pass approach because caching attention values from the scaling pass and then using them for the forward pass would invalidate results. We intend to begin work on integration with vLLM, which will require 2 KV caches: vllm-project/vllm#2890.

**Comment by JY-CCK** [comment]
Hi @EricLBuehler 
Thank you for the response. Actually, I didn't fully understand the concept of Dual forward pass in the paper. Could you provide more details? Especially in section 4.2.1, I'm not sure what scaling Λ is. Is it different from λ? 

Also, could you explain how to proceed with 'layerwise-scalings?
Is this mean 'model.set_scaling_pass_value(0)'?

**Comment by EricLBuehler** [comment]
The scalings Λ contains scalings for each layer, token, and adapter. The λ matrix contains scalings for each layer, and in Python terms can be thought of as indexing Λ.

**Comment by JY-CCK** [comment]
I think I've found the solution. 
Previously, after declaring the model with xlora, I used **model.enable_input_require_grads()**, 
but removing it resolved the issue. 

Anyway, 
Could you explain more about "Setting and resetting the scaling pass value and global LoRA weight"?
What is it for?

Thanks.

**Comment by EricLBuehler** [comment]
Glad to hear that! For future reference, configuration information including layerwise scalings, topk, and softmax can be found in the [`xLoRAConfig`](https://github.com/EricLBuehler/xlora/blob/master/README.md#x-lora-config) class.

**About the scalings and the dual forward pass scheme:**
The scalings Λ contains scaling values for each layer, token, and adapter. The λ matrix contains scalings for each layer, and in Python terms can be thought of as indexing Λ. We apply the scalings from λ to the input for each adapter by 
1) Indexing λ to get the scalings for the tokens for that adapter
2) Broadcast multiplying the resulting vector to the input for the adapter

**About "Setting and resetting the scaling pass value and global LoRA weight":**
This allows you to manually apply a coefficient to the output of each LoRA adapter. It acts like the alpha value in LoRA, and it is a granular parameter to increase the signal weight.

Additionally, we could share a training sample code, but we will be unable to provide it until the weekend.

**Comment by JY-CCK** [comment]
Thanks for your kind response!

**Comment by XiaoYiWeio** [comment]
> I think I've found the solution. Previously, after declaring the model with xlora, I used **model.enable_input_require_grads()**, but removing it resolved the issue.
> 
> Anyway, Could you explain more about "Setting and resetting the scaling pass value and global LoRA weight"? What is it for?
> 
> Thanks.

Hello, I encountered the same error as in your issue. I also removed model.enable_input_require_grads() as you suggested, but the error still persists:

```
loss: tensor(3.0876, device='cuda:0')
loss: tensor(3.0876, device='cuda:0')
Traceback (most recent call last):
  File "/mnt/petrelfs/zhangbo1/xlora/llmsafety_sft/finetune.py", line 402, in <module>
    train()
  File "/mnt/petrelfs/zhangbo1/xlora/llmsafety_sft/finetune.py", line 316, in train
    trainer.train()
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/transformers/trainer.py", line 3045, in training_step
    self.accelerator.backward(loss)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/accelerate/accelerator.py", line 1995, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 166, in backward
    self.engine.backward(loss, **kwargs)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1979, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2055, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 66, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/torch/_tensor.py", line 494, in backward
    torch.autograd.backward(
  File "/mnt/petrelfs/zhangbo1/anaconda3/envs/eval_py311/lib/python3.11/site-packages/torch/autograd/__init__.py", line 255, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
